<?php
defined('BASEPATH') OR exit('No direct script access allowed');
 
$config['barangay'] = [ 
    'APIL',
    'BINUANGAN',
    'BOLIBOL',
    'BUENAVISTA',
    'BUNGA',
    'BUNTAWAN',
    'BURGOS',
    'CANUBAY',
    'CLARIN SETTLEMENT',
    'DOLIPOS BAJO',
    'DOLIPOS ALTO',
    'DULAPO',
    'DULLAN NORTE',
    'DULLAN SUR',
    'LOWER LAMAC',
    'LAYAWAN',
    'LOWER LANGCANGAN',
    'LOWER LOBOC',
    'LOWER RIZAL',
    'MALINDANG',
    'MIALEN',
    'MOBOD',
    'CIRIACO C. PASTRANO',
    'PAYPAYAN',
    'PINES',
    'POBLACION I',
    'POBLACION II',
    'PROPER LANGCANGAN',
    'SAN VICENTE ALTO',
    'SAN VICENTE BAJO',
    'SEBUCAL',
    'SENOTE',
    'TABOC NORTE',
    'TABOC SUR',
    'TALAIRON',
    'TALIC',
    'TOLIYOK',
    'TIPAN',
    'TRANSVILLE',
    'TUYABANG ALTO',
    'TUYABANG BAJO',
    'TUYABANG PROPER',
    'UPPER LANGCANGAN',
    'UPPER LAMAC',
    'UPPER LOBOC',
    'UPPER RIZAL',
    'VICTORIA',
    'VILLAFLOR',  
]; 


$config['classification'] = [   
    'NON FOOD',
    'FOOD',
    
]; 